### ISSUE TITLE
Poor accuracy on self-collected dataset

### ISSUE THREAD

**Issue by linwk20** [YuePanEdward/MULLS#43]
Hi, Thanks for your sharing of this great work!

I have successfully run this work on my dataset which is collected using OS1-128 Lidar in a underground parking lot.
However, the performance is very poor (much worse than A-LOAM), I think I must mistake something. So I come here, and hope can be helped.

Should I modified any configuration in the code to accommodate to my own sensor or scene? 

Thanks for your reading!

**Comment by YuePanEdward** [comment]
Sorry for the late reply. 
You may try the [config file](https://github.com/YuePanEdward/MULLS/blob/main/script/config/lo_gflag_list_128.txt) used for 128 beam LiDAR. Besides, the motion undistortion module should be somehow corrected since OS1 begins scan from the positive direction of X axis anti-clockwise.
