### ISSUE TITLE
Teaser fails

### ISSUE THREAD

**Issue by ahandsomeperson** [YuePanEdward/MULLS#7]
Hi @YuePanEdward , thanks for your great work!
Now I am trying to use mulls_registration to align loop closure key submaps in indoor environment. However, the Teaser fails and no initial pose is provided for icp. 
The following pics shows that features from submaps seem abundant but teaser finds too few inliners.
![选区_884](https://user-images.githubusercontent.com/33352875/106981744-8a22e080-679d-11eb-8e05-bd32499e6ed8.png)
![选区_882](https://user-images.githubusercontent.com/33352875/106981790-a757af00-679d-11eb-867e-fcf46432468a.png)
And the following pic is my mulls_reg params:
![选区_883](https://user-images.githubusercontent.com/33352875/106981833-bb9bac00-679d-11eb-99e3-f1e27f43faa0.png)
So how to adjust params to make the teaser success?

Thanks!

**Comment by ahandsomeperson** [comment]
[pcd.zip](https://github.com/YuePanEdward/MULLS/files/5929815/pcd.zip)
Here is my pcd.

**Comment by YuePanEdward** [comment]
Sorry for the late reply and thanks for your interest.
However, it seems that TEASER does not perform quite well for this data for the following reasons:
1. The point cloud is flipped and the ground's normal seems to be parallel to x axis instead of z axis. This would undermine the feature extraction and encoding.
2. The used neighbour category context (NCC) feature is not descriptive enough when it is encoded based on sparse submap point cloud, especially for scenarios with lots of similar structures. 

After flipping back the point cloud, the extracted feature points seems (grey: ground, red: roof, blue: facade, green: pillar, yellow: beam) to be more reasonable.
![feature_points_after_flipping](https://user-images.githubusercontent.com/34207278/107716856-a14c5b80-6cd2-11eb-8817-cc53c5be6d14.png)

**Comment by ahandsomeperson** [comment]
Thank you for your reply!
The point cloud is actually parallel to x axis instead of z axis. Now I flipped back the point cloud, and  get similiar feature points as your results. However TEASER still does not perform quite. Maybe I need force matching?

**Comment by YuePanEdward** [comment]
Sorry for the late reply. 
Currently, the used local feature descriptor is efficient to encode but not descriptive enough. Therefore, when the overlapping ratio of the two submaps is low, the correspondence inlier ratio would also be quite low, which may lead to problems of TEASER.
I will keep working on solving this issue.
