### ISSUE TITLE
Performance about 03 sequence

### ISSUE THREAD

**Issue by LJY-RS** [YuePanEdward/MULLS#8]
Hi, thanks for your good work! I test the 03 sequence of kitti with both urban and highway configurations. However, the ATE is much worse than the one reported in your ICRA paper. The ATE is about 1.84%. The 00 and 01 sequences can get similar performance with your paper. I want to know how to set the parameter configration for 03? Thanks a lot!

**Comment by YuePanEdward** [comment]
Thanks for your interest. 
From my side, directly running run_mulls_slam.sh with the config file lo_gflag_list_kitti_urban.txt in this repository gives rise to the following results (ATE 0.62 %):

![kitti03_test](https://user-images.githubusercontent.com/34207278/109626400-cd743300-7b40-11eb-9528-fdd54e7c104d.png)
![kitti_03_result](https://user-images.githubusercontent.com/34207278/109626416-d107ba00-7b40-11eb-9309-44fba6aec36d.png)

which is a bit worse than the results reported in the paper due to different parameter setting. 

I guess that there might be some problem with the input data. For example, the calibration matrix might be incorrect or some of the frames are missing.

**Comment by LJY-RS** [comment]
Thanks, the problem is the calibration matrix. Then, I want to know how the vertical calibration angle 0.195 is obtained? Thanks a lot!

**Comment by YuePanEdward** [comment]
It is calibrated with the initial guess provided by the paper [1] and [2].
[1] J.E.  Deschaud,  “Imls-slam:  scan-to-model  matching  based  on  3ddata,”  in2018 IEEE International Conference on Robotics and Au-tomation (ICRA).    IEEE, 2018, pp. 2480–2485
[2] D. Yin, Q. Zhang, J. Liu, X. Liang, Y. Wang, J. Maanpää, H. Ma, J. Hyyppä and R. Chen: CAE-LO: LiDAR Odometry Leveraging Fully Unsupervised Convolutional Auto-Encoder for Interest Point Detection and Feature Description. 2020.
Thanks.
